name: publish

on:
  push:
    tags: [ v* ]
  workflow_dispatch:

jobs:
  build-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup dotNET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          6.x
          7.x
          8.x
          9.x
    - name: Get Version
      run: echo "VERSION=$(date '+%Y.%m%d')" >> $GITHUB_ENV
    - name: Build
      run: |
        dotnet pack --version-suffix ${{ env.VERSION }} -c Release -o out DH.NCode/DH.NCode.csproj
        dotnet pack --version-suffix ${{ env.VERSION }} -c Release -o out XCodeTool/XCodeTool.csproj
        dotnet pack --version-suffix ${{ env.VERSION }} -c Release -o out DH.NCode.MySql/DH.NCode.MySql.csproj
        dotnet pack --version-suffix ${{ env.VERSION }} -c Release -o out DH.NCode.SQLite/DH.NCode.SQLite.csproj
        dotnet pack --version-suffix ${{ env.VERSION }} -c Release -o out DH.NCode.SqlServer/DH.NCode.SqlServer.csproj
        dotnet pack --version-suffix ${{ env.VERSION }} -c Release -o out DH.NCode.Oracle/DH.NCode.Oracle.csproj
        dotnet pack --version-suffix ${{ env.VERSION }} -c Release -o out DH.NCode.PostgreSQL/DH.NCode.PostgreSQL.csproj
        dotnet pack --version-suffix ${{ env.VERSION }} -c Release -o out DH.NCode.DaMeng/DH.NCode.DaMeng.csproj
        dotnet pack --version-suffix ${{ env.VERSION }} -c Release -o out DH.NCode.DB2/DH.NCode.DB2.csproj
        dotnet pack --version-suffix ${{ env.VERSION }} -c Release -o out DH.NCode.KingBase/DH.NCode.KingBase.csproj
        dotnet pack --version-suffix ${{ env.VERSION }} -c Release -o out DH.NCode.HighGo/DH.NCode.HighGo.csproj
    - name: Publish
      run: |
        #dotnet nuget push ./out/*.nupkg --skip-duplicate --source https://nuget.pkg.github.com/PeiKeSmart/index.json --api-key ${{ github.token }}
        dotnet nuget push ./out/*.nupkg --skip-duplicate --source https://nuget.chuangchu.net/v3/index.json --api-key ${{ secrets.mynugetKey }}
        dotnet nuget push ./out/*.nupkg --skip-duplicate --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.nugetKey }}